return {
  require("configs.kanagawa"),
  require("configs.statusline"),
  require("configs.oil"),
  require("configs.copilot"),
  require("configs.auto-indent"),
  require("configs.treesitter"),
  require("configs.which-key"),
  require("configs.noice"),
  require("configs.fzf"),
  require("configs.project"),
  require("configs.tree"),
  require("configs.lsp"),
  -- require("configs.dressing"),
  require("configs.snacks"),
  require("configs.conform"),
  require("configs.blink"),
  require("configs.gitsigns"),
  require("configs.gitgraph"),
  require("configs.auto-pairs"),
  require("configs.surround"),
  require("configs.comment"),
  require("configs.treesitter-textobjects"),
  require("configs.hop"),
  require("configs.highlight-colors"),
  require("configs.silicon"),
}
